[build]
  functions = "serverless"
  publish = "public"

[dev]
  functions = "serverless"
  publish = "public"

[[plugins]]
package = "@uwhealth-public/netlify-plugin-jest"

  [plugins.inputs]
  skipTests = true

## Netlify offers the ability to configure the Redirects, Rewrites, Proxying and Headers directly in this *.toml configuration file. Please see the README for links to Netlify documentation.
## these are samples.

[[redirects]]
  from = "/hello-world/*"
  to = "/.netlify/functions/hello-world?person=:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect even if file present

# [[headers]]
#   for = "/.netlify/functions/hello-world"
#   [headers.values]
#   Basic-Auth = "foo:bar foo2:bar2"

# [[headers]]
#   for = "/hello-world/*"
#   [headers.values]
#   Basic-Auth = "foo:bar foo2:bar2"

#   [[headers]]
#   for = "/secret.html"
#   [headers.values]
#   Basic-Auth = "otherfoo:otherbar"
